# Generated by Django 6.0.3 on 2026-04-15 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_contact_delete_contactmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='payment_method',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='price',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='service',
            field=models.CharField(choices=[('Haircut & Style', 'Haircut & Style'), ('Balayage', 'Balayage'), ('Keratin Smoothing', 'Keratin Smoothing'), ('Deep conditioning', 'Deep conditioning'), ('Designer Haircut', 'Designer Haircut'), ('Holistic Facial Glow', 'Holistic Facial Glow'), ('Deep Tissue Ritual', 'Deep Tissue Ritual'), ('Signature Glow Facial', 'Signature Glow Facial'), ('Delox Body Scrub', 'Delox Body Scrub'), ('Bridal Makeup', 'Bridal Makeup'), ('Party Makeup', 'Party Makeup'), ('Daily Makeup', 'Daily Makeup'), ('Bridal & Party Makeup', 'Bridal & Party Makeup'), ('Basic Nail Polish Art', 'Basic Nail Polish Art'), ('French Manicure', 'French Manicure'), ('Gel Nail Art', 'Gel Nail Art'), ('Acrylic Nails Extensions', 'Acrylic Nails Extensions'), ('Dip Powder Nails', 'Dip Powder Nails'), ('3D Bridal Nails', '3D Bridal Nails'), ('Hair Cut Basic', 'Hair Cut Basic'), ('Hair Cut Advance', 'Hair Cut Advance'), ('Hair Wash + Styling', 'Hair Wash + Styling'), ('Beard Trim', 'Beard Trim'), ('Beard Styling/Design', 'Beard Styling/Design'), ('Clean Shave', 'Clean Shave'), ('Hair Color', 'Hair Color'), ('Beard Color', 'Beard Color'), ('Highlights/Streaks', 'Highlights/Streaks'), ('Cleanup', 'Cleanup'), ('Facial', 'Facial'), ('De Tan Facial', 'De Tan Facial'), ('Head Massage', 'Head Massage'), ('Hair Spa', 'Hair Spa'), ('Body Massage', 'Body Massage'), ('Manicure', 'Manicure'), ('Pedicure', 'Pedicure'), ('Waxing', 'Waxing')], max_length=100),
        ),
    ]
